### ISSUE TITLE
Make the assertions chainable

### ISSUE THREAD

**Issue by Windvis** [simplabs/qunit-dom#177]
What do you think about making it possible to chain assertions? That way you don't have to call `assert.dom()` multiple times (or cache it).

```javascript
assert.dom('.some-class')
  .exists()
  .hasText('Testing')
  .hasAttribute('disabled');
```

**Comment by Turbo87** [comment]
I'm trying to remember. I think there was a reason that prevented it, but I don't recall what it was... 🤔

**Comment by amk221** [comment]
This is a great idea, but imagine:

```javascript
assert.dom('.filter:nth-child(1)')
  .hasClass('.is-applied')
  .hasText('Open');
```

Where might one put the assertion description "The Open filter is applied"?

**Comment by Turbo87** [comment]
no, but I think one things that could be confusing about this, is that when `assert.expect()` is used, it is not clear what parts of the chained assertions are assertions, or if it's just a single assertion. with `chai` this doesn't matter so much because Mocha and e.g. Jest don't do assertion tracking, but QUnit does, which makes this feel a little weird 🤔

**Comment by chriskrycho** [comment]
Just came here (after working on a bunch of docs) to suggest this—because I actually came to double-check that it worked, after assuming it did but realizing I wasn’t positive. I’d be curious to see if we can identify concrete blockers and make it work!

**Comment by deyshin** [comment]
I came here while researching if this is allowed. 
Have we found a strong reason to block this?
