### ISSUE TITLE
Allow for pseudo element styles to be checked

### ISSUE THREAD

**Issue by joankaradimov** [simplabs/qunit-dom#229]
I'd like to suggest a new assertion - `hasPseudoElementStyle`. The usage should be something like:

```javascript
assert.dom('.progress-bar').hasPseudoElementStyle(':before', {
  content: '"something"'
});
```

AFIK the only way to implement this is via the second argument of [getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle). And `qunit-dom` never uses it. This can also be achieved with an additional optional argument to `hasStyle`, but that would change a public API.

If either of these sounds reasonable I could implement it.

**Comment by Turbo87** [comment]
interesting... I assume `assert.dom('.progress-bar::before').hasStyle(...)` does not work?

**Comment by joankaradimov** [comment]
> I assume assert.dom('.progress-bar::before').hasStyle(...) does not work?
No, there is a call to `findTargetElement` and it does not return anything meaningful with that selector.

**Comment by Turbo87** [comment]
> No, there is a call to `findTargetElement` and it does not return anything meaningful with that selector.

yeah, I guess that makes sense as it's not a real selectable element

our options are:

1) implement `assert.dom(...).hasPseudoElementStyle(...)`
2) add an options hash to `assert.dom(...).hasStyle(styles, [options], [message])`
3) support pseudo element selectors `assert.dom('foo::before').hasStyle(...)`

the third option looks nice on first glance but then the selector would no longer be tied to `querySelector()` semantics and something like `assert.dom('foo::before').exists()` would fail in unexpected ways 🤔 

the second option would be somewhat consistent with the other assertions, but since we would have two hashes in the call it might look weird.

I think I tend to prefer the first option for now, and we could still implement the others later if we realize that it was the wrong choice.

> Should I try to implement this or will someone else work on it?

PRs are very welcome :)

**Comment by joankaradimov** [comment]
I wrote a little something which [can be seen here](https://github.com/joankaradimov/qunit-dom/commits/get-pseudo-element-style). But unfortunately, the test I wrote does not work because the implementation of `getComputedStyle` in `jsdom` is incomplete:

https://github.com/jsdom/jsdom/blob/0c4deecfc98dcfb318425124a4b5a8eed3227be4/lib/jsdom/browser/Window.js#L498

There is an issue opened for that in `jsdom`:
https://github.com/jsdom/jsdom/issues/1928

**Comment by Turbo87** [comment]
@joankaradimov looks good. maybe instead we can implement at least a small smoke test in the Ember test suite that runs in an actual browser. since the implementation shares most of the logic with the `hasStyle()` I guess it's already tested well enough.
