### ISSUE TITLE
How to find specific number of element?

### ISSUE THREAD

**Issue by Mifrill** [simplabs/qunit-dom#400]
Thank you for lib. Great work!

Unfortunately, can't find the specific element with current syntax, please help.
For example on Jquery: `.eq()`, but how it works here?
https://api.jquery.com/eq/

```
assert.dom('.tabs a').eq(0)
assert.dom('.tabs a[0]')
assert.dom('.tabs a(0)')
assert.dom('.tabs a:eq(0)')
assert.dom('.tabs a')[0]
```
all of them didn't work.
also docs has no provide the example:
https://github.com/simplabs/qunit-dom/blob/master/API.md
Please, if possible - add this. Thank you

**Comment by Turbo87** [comment]
the problem is that `:eq()` is something specific to jQuery, but qunit-dom explicitly does not use jQuery. you can try out the `:nth-child()` CSS selector (https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) which can do something roughly similar.

in short: qunit-dom supports everything that `document.querySelector()` supports (see https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector)
