### ISSUE TITLE
hasCount assertion

### ISSUE THREAD

**Issue by mupkoo** [simplabs/qunit-dom#456]
I find myself that I am using `exists({ count: 4 })` quite often and I was thinking that a shorthand will be useful - `hasCount`. Some other name might do, but this is more or less in line with `exists`.

```javascript
assert.dom('[data-test-post]').hasCount(3); // I find this easier to write and read
assert.dom('[data-test-post]').exists({ count: 3 });
```

I can create a PR if you think that this is a good idea as well.

**Comment by Turbo87** [comment]
For `exists({ count: 0 })` you can use `doesNotExist()` instead. I'm not convinced that we need an additional dedicated assertion for this 🤔

**Comment by mupkoo** [comment]
Bad example with `exists({ count: 0 })`. I just wanted to say that I am using `exists({ count })`. 

Two benefits that I see in having `hasCount`:
1. Easier to write and read
2. It will get suggested by your editor

(The first time I tried the package, I was looking for something similar in the auto-suggest box of my editor)

**Comment by mansona** [comment]
Hey folks 👋 

I don't really have an opinion on if this API should exist or not, but I'm not too sure I like the name `hasCount()` 🤔 the issue is that we have other APIs like `hasClass()` that is checking for a value in `someElement.class` and if we have a consistent API then `hasCount()` would imply checking for the value `someElement.count` 🙈 

I don't really have a suggestion for a better name here but I think it matters what we name this to avoid any confusion

**Comment by mupkoo** [comment]
It might be just `count|size|length`

```javascript
assert.dom('[data-test-post]').count(3);
assert.dom('[data-test-post]').size(3);
assert.dom('[data-test-post]').length(3);
```
