### ISSUE TITLE
Increase cohesion with ember-test-selectors

### ISSUE THREAD

**Issue by bantic** [simplabs/qunit-dom#72]
Would there be interest in either modifying how the `hasValue` method works or adding a new one that works well with data-test-* attribute selectors?

A common pattern we use is: `assert.dom('[data-test-record-id="1"]').exists()`. This fails with the same message if either the data-test-record-id attr is not present or it is present but has a different value. It would make our tests easier to work with if we could do something like:

`assert.dom('[data-test-record-id]').hasValue("1")`

And then this could fail with one useful message if data-test-record-id is missing, or a useful diff when it is present but has a value other than "1".

Overloading the `hasValue` method doesn't seem quite right, so perhaps this is an enhancement request, to add a new method. Maybe `hasSelectorValue`?
If there's interest in adding this I'd be happy to make a PR for it.

**Comment by Turbo87** [comment]
as you noticed, `assert.dom('[data-test-record-id]').hasValue("1")` is not an option because `hasValue()` already has quite a different meaning.

I'm not opposed to something like `hasSelectorValue()`, but we should plan out how the API would look like. I'm assuming what you want is:
```js
assert.dom('[data-test-record-id]').hasSelectorValue('1');
```
which would roughly be shorthand for something like
```js
assert.dom('[data-test-record-id]').hasAttribute('data-test-record-id', '1');
```

The things that we would need to clarify:

- how do we extract the selector from the selector string? do we only extract `data-test-` attributes? only `data-` attributes? all attributes? only attributes without a value?
- what happens if you pass an `HTMLElement` to `assert.dom()` instead of a string selector and then call `hasSelectorValue()`?
- should we offer a variant of `hasSelectorValue()` where you can pass in the selector name (`data-test-record-id` in this case)?

**Comment by bantic** [comment]
Thanks for the detailed response here.

My thoughts on your clarification questions:

  * Extracting the selector from selector string: I was thinking to use the attribute at the end of the string (e.g. by using a regex to test for `/\[.*\]$/`). So `'[data-test-foo="bar"] [data-test-id]'` would extract "data-test-id" as the attribute, and `"#foo input[name]"` would extract "name" and so on. If no attribute could be extracted that would be an error.
  * A variant where you pass in a selector name doesn't seem needed to me if we use the heuristic above and since that case is also possible now via the `hasAttribute` method.
  * I wasn't aware that an `HTMLElement` is a valid argument to `assert.dom()` — This seems like it shouldn't be supported as there's no good way that I can think of to determine which of the element's attributes is intended. So the `hasSelectorValue` could simply throw in this case.

**Comment by bantic** [comment]
Yeah, it may be a bit too magical. I may start by implementing this as a custom helper in our app and see how it feels. If we come to a consensus here I'd be happy to make a PR to add it to qunit-dom as well.

I agree that it's not quite a perfect fit. I keep staring at the redundancy in our tests (`assert.dom('[X]').hasAttribute(X, ...)` and wanting to DRY it up. :)

**Comment by happycollision** [comment]
What about a slightly different namespace?

```
assert.dom.selector('[x]').hasValue('y');
assert.dom.selector('[x]', {count: 7}).haveValue('y');
assert.dom.selector('[x]', {count: 3}).haveValues(['1', '2', '3']);
```
or
```
assert.dom.selector('[x]').hasValue('y');
assert.dom.selectors('[x]', 7).haveValue('y');
assert.dom.selectors('[x]', 3).haveValues(['1', '2', '3']);
```

Or any variation thereof.

**Comment by Turbo87** [comment]
What's the advantage over writing out the full selector? How would that proposal handle nested test selectors?

**Comment by happycollision** [comment]
Sorry to be confusing. The "x" was in place of a full selector. My proposal is that adding `.selector` after `.dom` could signal that we are looking at the value of the selector itself, not the element that we selected with it. I'll re-do my mock example, without all the additional semantic variations:

```
assert.dom.selector('[data-some-selector]').hasValue('y');
assert.dom.selector('.links [href]').hasValue('http://example.com');
```

It solves a few of the issues above.

> this would introduce a little too much "magic" to the library

Since you are using the `selector` namespace, there is no confusion that you are doing something new here. Additionally, you wouldn't have to do anything new or special in the `dom()` function.

> * what happens if you pass an `HTMLElement` to `assert.dom()` instead of a string selector and then call `hasSelectorValue()`?

No. `assert.dom.selector()` could require a string as its first argument.

----------

The `dom.selector()` function could return an object that only has two methods on it:
1. hasValue
2. haveValues

The first could take a single value. If the selector returns multiple DOM elements, the first one is used for comparison.

`haveValues()` could take an array whose length must be less than or equal to the number of elements selected. Each value in the array would be compared to the corresponding element's attribute value. It could also take a string, which it would then compare to the attribute values of every selected element.

I suppose that both could take an optional second parameter that would be an object which looks like `{count: 3}` like you've already done for `exists`. But maybe not.

----------
Separately, regarding

> > `#foo input[name]` would extract `name`
> 
> this seems quite confusing/surprising to me 🤔

Anecdotally, the use of the very last attribute in a selector was exactly what I was thinking even before I read @bantic's clarification on the subject.

**Comment by Turbo87** [comment]
I don't see what the advantage of `assert.dom.selector('[data-some-selector]').hasValue('y');` over `assert.dom('[data-some-selector]').hasValue('y');` is

**Comment by lindem** [comment]
I am sorry to ask this, but when #206 is done, that use case is probably covered by 

```
assert.dom('[data-test-record]').matchesSelector('[data-test-record="1"]');
```

Does that resolve this issue or am I misunderstanding what's asked here?
