### ISSUE TITLE
Typescript Type Definitions

### ISSUE THREAD

**Issue by josemarluedke** [simplabs/qunit-dom#94]
Hey there! 

Working with this addon is amazing, however, working with this and TypeScript is not great as it doesn't have type definitions. 

Do you have intention on adding Type Definitions to easy integrate with Ember apps using TypeScript?

**Comment by Turbo87** [comment]
there is a type definition available at https://yarnpkg.com/en/package/@types/qunit-dom

I'm hesitant to include it in this project itself since it will most likely go out of sync. I'd rather port the whole project to TypeScript instead, but as you're probably aware this is a somewhat more significant effort.
