### ISSUE TITLE
hasStyle - unuseful serialization in CI

### ISSUE THREAD

**Issue by lifeart** [simplabs/qunit-dom#946]
![image](https://user-images.githubusercontent.com/1360552/103285271-b5701e00-49ee-11eb-8310-a56cfb9fa8ff.png)

it will be great to have meaningful diff, could we redefine `toString`, to have kinda

`obj.toString = () => JSON.stringify(ob)` ?

in browser all looks good
![image](https://user-images.githubusercontent.com/1360552/103285581-9cb43800-49ef-11eb-87d4-49a55a54dad9.png)

**Comment by Turbo87** [comment]
while I agree that the CLI output doesn't look great, I think this is probably more something that should be addressed in `testem`, which creates that output. maybe it should serialize JS objects properly instead of just writing `[object Object]`. is it the same problem when using the regular `assert.deepEqual()`?
